const main_white = "#fff";
const secondary_dark = "#343845";
export const light = {
	navbar_color: main_white,
	navbar_user_name_color: secondary_dark,
	social_colors: "#292929",
	body_color: "#dae2e2",
	component_main_color: "white",
	sidebar_color: main_white,
	sidebar_tab_icon_color: secondary_dark,
	feed_post_color: main_white,
	feed_post_title_color: "#000",
	feed_post_title_hover_color: "#0000ff",
	feed_post_text_color: "#404040",
	feed_post_author_name_color: "#505050",
	feed_post_author_name_hover_color: "#222222",
	feed_post_publish_date_color: "#575757",
	feed_post_publish_date_hover_color: "#282828",
	feed_post_tag_text_color: "#9aadac",
	feed_post_tag_hover_background_color: "#9aadac",
	feed_post_tag_hover_outline_color: "#dfdfdf",
	homepage_sidebar_tab_text_color: secondary_dark,
	homepage_sidebar_tab_icon_color: secondary_dark,
	homepage_sidebar_tab_hover_color: "",
	homepage_post_options_text_color: "#555555",
	homepage_post_options_hover_text_color: "#2f2f2f",
	homepage_post_options_save_background_color: "gray",
	homepage_post_options_save_hover_background_color: "#c4c4c4",
	homepage_post_options_save_hover_text_color: main_white,
	homepage_post_options_save_text_color: main_white,
};
